<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by Image Hosting Service</title>
</head>
<body>
    {{-- <h1>{{ $user['name'] }}</h1>
    <p>{{ $user['info'] }}</p> --}}
    <a href="{{ $details['link']}}">Click Here to save temp pass:</a>
    <p>Thank you</p>
</body>
</html>
